CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_ENRICHED (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    ENRICHED_NAME VARCHAR(100)
);